package com.sdet; 
import org.testng.Assert; 
import org.testng.annotations. Test; 
 
Run All 
public class AppTest { 
 
8-@Test 
Run Debug 
public void testlogini() 
{ 
9 
10 
11 App myapp-new App(); 
12 
Assert.assertEquals(e, myapp.userLogin("abc", "abc123")); 
13 } 
14 
15 @Test 
Run Debug 
public void testlogin2() 
17 { 
18 
19 
App myapp-new App(); 
Assert.assertEquals(1, myapp.userLogin("abc", "abc@123")); 
16 
20 } 
21 
22} 
23 